"""add table for delivery methods

Revision ID: 58fd0f754267
Revises: 8d6bd1b12e07
Create Date: 2025-07-05 22:10:15.815987

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

delivery_method_enum = postgresql.ENUM(
    "TELEGRAM", "EMAIL", name="deliverymethod", create_type=True
)

# revision identifiers, used by Alembic.
revision: str = "58fd0f754267"
down_revision: Union[str, Sequence[str], None] = "8d6bd1b12e07"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "delivery_methods",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("delivery_method", delivery_method_enum, nullable=False),
        sa.Column("contact_value", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "delivery_method",
            "contact_value",
            name="uq_user_method_contact",
        ),
    )
    op.create_index(
        op.f("ix_delivery_methods_user_id"),
        "delivery_methods",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_delivery_methods_user_id"), table_name="delivery_methods")
    op.drop_table("delivery_methods")
    # ### end Alembic commands ###
