"""add storing delivery methods

Revision ID: 3009cd96833e
Revises: 2b469c6f3817
Create Date: 2025-09-20 00:32:51.292675

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3009cd96833e"
down_revision: Union[str, Sequence[str], None] = "2b469c6f3817"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reminder_delivery_method",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("reminder_id", sa.Uuid(), nullable=False),
        sa.Column("delivery_method_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["delivery_method_id"], ["delivery_methods.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["reminder_id"], ["reminders.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reminder_delivery_method_reminder_id"),
        "reminder_delivery_method",
        ["reminder_id"],
        unique=False,
    )
    op.add_column(
        "delivery_methods", sa.Column("user_id", sa.Uuid(), nullable=False)
    )
    op.drop_index(
        op.f("ix_delivery_methods_reminder_id"), table_name="delivery_methods"
    )
    op.drop_constraint(
        op.f("uq_user_method_contact"), "delivery_methods", type_="unique"
    )
    op.create_unique_constraint(
        "uq_user_method_contact",
        "delivery_methods",
        ["delivery_method", "contact_value", "user_id"],
    )
    op.drop_constraint(
        op.f("delivery_methods_reminder_id_fkey"),
        "delivery_methods",
        type_="foreignkey",
    )
    op.drop_column("delivery_methods", "reminder_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "delivery_methods",
        sa.Column(
            "reminder_id", sa.UUID(), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key(
        op.f("delivery_methods_reminder_id_fkey"),
        "delivery_methods",
        "reminders",
        ["reminder_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "uq_user_method_contact", "delivery_methods", type_="unique"
    )
    op.create_unique_constraint(
        op.f("uq_user_method_contact"),
        "delivery_methods",
        ["reminder_id", "delivery_method", "contact_value"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_delivery_methods_reminder_id"),
        "delivery_methods",
        ["reminder_id"],
        unique=False,
    )
    op.drop_column("delivery_methods", "user_id")
    op.drop_index(
        op.f("ix_reminder_delivery_method_reminder_id"),
        table_name="reminder_delivery_method",
    )
    op.drop_table("reminder_delivery_method")
    # ### end Alembic commands ###
