"""add inactive status

Revision ID: e388ce31ecc9
Revises: 3009cd96833e
Create Date: 2025-09-23 22:00:03.517610

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e388ce31ecc9"
down_revision: Union[str, Sequence[str], None] = "3009cd96833e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE status ADD VALUE IF NOT EXISTS 'INACTIVE';")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
