"""add delivery methods relationship

Revision ID: 9c8d16f8c7aa
Revises: 8d9906b30d41
Create Date: 2025-07-08 16:27:27.402622

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

delivery_enum = postgresql.ENUM(
    "TELEGRAM", "EMAIL", name="deliverymethodenum", create_type=True
)


# revision identifiers, used by Alembic.
revision: str = "9c8d16f8c7aa"
down_revision: Union[str, Sequence[str], None] = "8d9906b30d41"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "delivery_methods",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("reminder_id", sa.Uuid(), nullable=False),
        sa.Column(
            "delivery_method",
            delivery_enum,
            nullable=False,
        ),
        sa.Column("contact_value", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["reminder_id"], ["reminders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "reminder_id",
            "delivery_method",
            "contact_value",
            name="uq_user_method_contact",
        ),
    )
    op.create_index(
        op.f("ix_delivery_methods_reminder_id"),
        "delivery_methods",
        ["reminder_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_delivery_methods_reminder_id"), table_name="delivery_methods"
    )
    op.drop_table("delivery_methods")
    # ### end Alembic commands ###
