"""add reminder status

Revision ID: c9a743f20c3f
Revises:
Create Date: 2025-07-03 18:37:57.813363

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

status_enum = postgresql.ENUM(
    "PENDING", "PROCESSING", "SENT", "FAILED", name="status", create_type=True
)

# revision identifiers, used by Alembic.
revision: str = "c9a743f20c3f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "reminders",
        sa.Column("status", status_enum, nullable=False, server_default="PENDING"),
    )
    op.create_index(
        op.f("ix_reminders_remind_date"),
        "reminders",
        ["remind_date"],
        unique=False,
    )
    op.create_index(op.f("ix_reminders_status"), "reminders", ["status"], unique=False)
    op.create_index(
        op.f("ix_reminders_user_id"), "reminders", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reminders_user_id"), table_name="reminders")
    op.drop_index(op.f("ix_reminders_status"), table_name="reminders")
    op.drop_index(op.f("ix_reminders_remind_date"), table_name="reminders")
    op.drop_column("reminders", "status")
    # ### end Alembic commands ###
