"""add reminder status

Revision ID: 8d9906b30d41
Revises: 4c810d92db77
Create Date: 2025-07-07 22:40:36.582577

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

status_enum = postgresql.ENUM(
    "PENDING", "PROCESSING", "SENT", "FAILED", name="status", create_type=True
)

# revision identifiers, used by Alembic.
revision: str = "8d9906b30d41"
down_revision: Union[str, Sequence[str], None] = "4c810d92db77"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "reminders",
        sa.Column("status", status_enum, nullable=False, server_default="PENDING"),
    )
    op.create_index(op.f("ix_reminders_status"), "reminders", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reminders_status"), table_name="reminders")
    op.drop_column("reminders", "status")
    # ### end Alembic commands ###

    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        status_enum.drop(bind, checkfirst=True)
