"""initial

Revision ID: cd6f3a988315
Revises:
Create Date: 2025-10-15 18:39:39.599710

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cd6f3a988315"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "delivery_methods",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "delivery_method",
            sa.Enum("TELEGRAM", "EMAIL", name="deliverymethodenum"),
            nullable=False,
        ),
        sa.Column("contact_value", sa.String(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "meta_data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "delivery_method",
            "contact_value",
            "user_id",
            name="uq_user_method_contact",
        ),
    )
    op.create_table(
        "reminders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("remind_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "SENT", "FAILED", "INACTIVE", name="status"),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column("edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reminders_remind_date"),
        "reminders",
        ["remind_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reminders_status"), "reminders", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_reminders_user_id"), "reminders", ["user_id"], unique=False
    )
    op.create_table(
        "reminder_delivery_method",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("reminder_id", sa.Uuid(), nullable=False),
        sa.Column("delivery_method_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["delivery_method_id"], ["delivery_methods.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["reminder_id"], ["reminders.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reminder_delivery_method_reminder_id"),
        "reminder_delivery_method",
        ["reminder_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_reminder_delivery_method_reminder_id"),
        table_name="reminder_delivery_method",
    )
    op.drop_table("reminder_delivery_method")
    op.drop_index(op.f("ix_reminders_user_id"), table_name="reminders")
    op.drop_index(op.f("ix_reminders_status"), table_name="reminders")
    op.drop_index(op.f("ix_reminders_remind_date"), table_name="reminders")
    op.drop_table("reminders")
    op.drop_table("delivery_methods")
    # ### end Alembic commands ###
