services:
  db:
    image: postgres:17.6
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_LOGGING_COLLECTOR: "off"
      POSTGRES_LOG_MIN_MESSAGES: fatal
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    tmpfs:
      - /var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      TEST_DB_HOST: db
      TEST_DB_PORT: 5432
      TEST_DB_USER: test_user
      TEST_DB_PASS: test_password
      TEST_DB_NAME: test_db

    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
