"""add confirm status for delivery methods

Revision ID: 99e0e2d10fb3
Revises: 30ff370e11e0
Create Date: 2025-07-09 15:26:22.122559

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "99e0e2d10fb3"
down_revision: Union[str, Sequence[str], None] = "30ff370e11e0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "delivery_methods",
        sa.Column(
            "is_confirmed",
            sa.Boolean(),
            server_default="FALSE",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("delivery_methods", "is_confirmed")
    # ### end Alembic commands ###
