"""add delivery methods relationship

Revision ID: 30ff370e11e0
Revises: e910b20c617a
Create Date: 2025-07-08 19:03:44.509025

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "30ff370e11e0"
down_revision: Union[str, Sequence[str], None] = "e910b20c617a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("delivery_methods_user_id_fkey"),
        "delivery_methods",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_delivery_methods_user_id_cascade",
        "delivery_methods",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_delivery_methods_user_id_cascade", "delivery_methods", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("delivery_methods_user_id_fkey"),
        "delivery_methods",
        "users",
        ["user_id"],
        ["id"],
    )
    # ### end Alembic commands ###
