"""add storing user name for telegram

Revision ID: 834e18b9d241
Revises: 276a1ebce697
Create Date: 2025-09-19 01:41:26.985780

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "834e18b9d241"
down_revision: Union[str, Sequence[str], None] = "276a1ebce697"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "delivery_methods",
        sa.Column(
            "meta_data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.execute(
        "UPDATE delivery_methods SET meta_data = '{}'::jsonb WHERE meta_data IS NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("delivery_methods", "meta_data")
    # ### end Alembic commands ###
