"""init

Revision ID: e910b20c617a
Revises:
Create Date: 2025-07-07 13:35:51.678429

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

delivery_method_enum = postgresql.ENUM(
    "TELEGRAM", "EMAIL", name="deliverymethod", create_type=True
)


# revision identifiers, used by Alembic.
revision: str = "e910b20c617a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "delivery_methods",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "delivery_method",
            delivery_method_enum,
            nullable=False,
        ),
        sa.Column("contact_value", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "delivery_method",
            "contact_value",
            name="uq_user_method_contact",
        ),
    )
    op.create_index(
        op.f("ix_delivery_methods_user_id"),
        "delivery_methods",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_delivery_methods_user_id"), table_name="delivery_methods")
    op.drop_table("delivery_methods")
    op.drop_table("users")
    # ### end Alembic commands ###
